* The subdir_push/subdir_pop commands keep more state so that   various commands can find files in the test directory. * Added `need_files' command which can copy source across from   the srcdir (if we ever use a separate build) or down from   the test directory after a subdir_push. * Defined ${top_,}{build,src}dir.

diff --git a/test/test015/runtest b/test/test015/runtest
--- a/test/test015/runtest
+++ b/test/test015/runtest
@@ -7,12 +7,13 @@ init
 
 SUBTESTS="$@"
 if [ -z "$SUBTESTS" ] ; then
-    SUBTESTS=$(ls *.graph | sed -e 's|^.*/\(.*\)\.graph$|\1|')
+    SUBTESTS=$(ls $srcdir/*.graph | sed -e 's|^.*/\(.*\)\.graph$|\1|')
 fi
 
 for st in $SUBTESTS ; do
     subtest $st
-    $srcdir/graphgen.pl $srcdir/$st.graph $srcdir/${st}f.c $srcdir/${st}m.c || continue
+    perl $(_srcfile graphgen.pl) $(_srcfile $st.graph) ${st}f.c ${st}m.c \
+	|| fatal "Can't generate source from graph $st.graph"
     compile_c ${st}f.c
     compile_c ${st}m.c
     link $st ${st}f.o ${st}m.o
@@ -20,5 +21,6 @@ for st in $SUBTESTS ; do
     run_gcov ${st}f.c
     run_tggcov ${st}f.c
     compare_lines ${st}f.c
+    vdo $top_builddir/${_DUP}src/tggcov -G ${st}f.c
 done
 
